# Generated by Django 6.0.7 on 2026-07-19 17:28

import django.core.validators
import django.db.models.deletion
import gestion_hotel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabanas',
            fields=[
                ('id_cabana', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cabana', models.CharField(max_length=50, unique=True, verbose_name='Número de cabaña')),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad')),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio por noche')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservada', 'Reservada'), ('Ocupada', 'Ocupada'), ('Mantenimiento', 'Mantenimiento'), ('Inactiva', 'Inactiva')], default='Disponible', max_length=20, verbose_name='Estado')),
                ('nombre_cabana', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la cabaña')),
                ('tipo_cabana', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de cabaña')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('servicios_incluidos', models.TextField(blank=True, null=True, verbose_name='Servicios incluidos')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cabanas/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
            },
        ),
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id_funcion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_pelicula', models.CharField(max_length=150, verbose_name='Título de la película')),
                ('fecha_proyeccion', models.DateField(verbose_name='Fecha de proyección')),
                ('hora_proyeccion', models.TimeField(verbose_name='Hora de proyección')),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de entrada')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('duracion_minutos', models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración en minutos')),
                ('capacidad_sala', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad de la sala')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cine/', verbose_name='Imagen')),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20, verbose_name='Estado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('Cédula', 'Cédula'), ('RUC', 'RUC'), ('Pasaporte', 'Pasaporte')], default='Cédula', max_length=20, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[gestion_hotel.validators.validate_cedula_ruc], verbose_name='Número de documento')),
                ('nombres', models.CharField(max_length=150, validators=[gestion_hotel.validators.validate_letters_only], verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, validators=[gestion_hotel.validators.validate_letters_only], verbose_name='Apellidos')),
                ('telefono_celular', models.CharField(max_length=20, validators=[gestion_hotel.validators.validate_phone], verbose_name='Teléfono celular')),
                ('pais_origen', models.CharField(blank=True, default='', max_length=80, verbose_name='País de origen')),
                ('ciudad', models.CharField(blank=True, default='', max_length=80, verbose_name='Ciudad')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, validators=[gestion_hotel.validators.validate_email_format], verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=255, validators=[gestion_hotel.validators.validate_password_strength], verbose_name='Contraseña')),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('gerente', 'Gerente')], default='cliente', max_length=20, verbose_name='Rol')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.CharField(max_length=10, unique=True, verbose_name='Número de habitación')),
                ('tipo_habitacion', models.CharField(max_length=50, verbose_name='Tipo de habitación')),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio por noche')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservada', 'Reservada'), ('Ocupada', 'Ocupada'), ('Mantenimiento', 'Mantenimiento'), ('Inactiva', 'Inactiva')], default='Disponible', max_length=20, verbose_name='Estado')),
                ('imagen', models.ImageField(blank=True, help_text='Sube una imagen de la habitación (JPG, PNG, GIF).', null=True, upload_to='habitaciones/', verbose_name='Imagen')),
                ('capacidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('piso', models.CharField(blank=True, max_length=20, null=True, verbose_name='Piso o ubicación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='ResortDia',
            fields=[
                ('id_resort_dia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del área o servicio')),
                ('tipo_area', models.CharField(choices=[('piscina', 'Piscina'), ('habitacion_dia', 'Habitación del Día'), ('area_recreativa', 'Área Recreativa'), ('area_consumo', 'Área de Consumo'), ('restaurante', 'Restaurante'), ('spa', 'Spa'), ('cancha', 'Cancha'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('capacidad_maxima', models.IntegerField(verbose_name='Capacidad máxima')),
                ('requiere_reserva', models.BooleanField(default=False, verbose_name='Requiere reserva')),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo adicional')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Mantenimiento', 'Mantenimiento'), ('Inactivo', 'Inactivo')], default='Disponible', max_length=20, verbose_name='Estado')),
                ('horario_apertura', models.TimeField(blank=True, null=True, verbose_name='Horario de apertura')),
                ('horario_cierre', models.TimeField(blank=True, null=True, verbose_name='Horario de cierre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='resort_dia/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Resort Día',
                'verbose_name_plural': 'Resort Día',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('estado_reserva', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('No presentado', 'No presentado'), ('En curso', 'En curso'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=20, verbose_name='Estado de reserva')),
                ('codigo_reserva', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de reserva')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20, verbose_name='Estado de pago')),
                ('metodo_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta')], default='Pendiente', max_length=30, verbose_name='Método de pago')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_hotel.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='DetalleHabitaciones',
            fields=[
                ('id_detalle_hab', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_noches', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de noches')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('fecha_entrada', models.DateField(blank=True, null=True, verbose_name='Fecha de entrada')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_hotel.habitaciones', verbose_name='Habitación')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_hotel.reservas', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Detalle de Habitación',
                'verbose_name_plural': 'Detalles de Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleCine',
            fields=[
                ('id_detalle_cine', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_asientos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de asientos')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('fecha_uso', models.DateField(blank=True, null=True, verbose_name='Fecha de uso')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('id_funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_hotel.cine', verbose_name='Función')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_hotel.reservas', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Detalle de Cine',
                'verbose_name_plural': 'Detalles de Cine',
            },
        ),
        migrations.CreateModel(
            name='DetalleCabanas',
            fields=[
                ('id_detalle_cab', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_noches', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de noches')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('fecha_entrada', models.DateField(blank=True, null=True, verbose_name='Fecha de entrada')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('id_cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_hotel.cabanas', verbose_name='Cabaña')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_hotel.reservas', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Detalle de Cabaña',
                'verbose_name_plural': 'Detalles de Cabañas',
            },
        ),
        migrations.CreateModel(
            name='DetalleResort',
            fields=[
                ('id_detalle_resort', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_personas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de personas')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('fecha_uso', models.DateField(blank=True, null=True, verbose_name='Fecha de uso')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_hotel.reservas', verbose_name='Reserva')),
                ('id_resort_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_hotel.resortdia', verbose_name='Resort Día')),
            ],
            options={
                'verbose_name': 'Detalle Reserva',
                'verbose_name_plural': 'Detalles de Reserva',
            },
        ),
    ]
