# Generated by Django 6.0.7 on 2026-07-23 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaHospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('Habitacion', 'Habitación'), ('Cabana', 'Cabaña')], max_length=20, verbose_name='Tipo de servicio')),
                ('nombre_servicio', models.CharField(max_length=150, verbose_name='Nombre del servicio')),
                ('capacidad_personas', models.PositiveIntegerField(default=1, verbose_name='Capacidad de personas')),
                ('programa', models.CharField(choices=[('2D1N', '2 días / 1 noche'), ('3D2N', '3 días / 2 noches'), ('4D3N', '4 días / 3 noches')], max_length=20, verbose_name='Programa')),
                ('precio_ocupacion_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ocupación total')),
                ('tipo_ocupacion_secundaria', models.CharField(choices=[('Sencilla', 'Ocupación sencilla'), ('Doble', 'Ocupación doble')], default='Sencilla', max_length=20, verbose_name='Tipo ocupación secundaria')),
                ('precio_ocupacion_secundaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ocupación secundaria')),
                ('incluye_iva', models.BooleanField(default=True, verbose_name='Incluye IVA')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa de hospedaje',
                'verbose_name_plural': 'Tarifas de hospedaje',
                'ordering': ['tipo_servicio', 'nombre_servicio', 'programa'],
            },
        ),
        migrations.AddField(
            model_name='cine',
            name='dia_funcion',
            field=models.CharField(default='Sábado', max_length=30, verbose_name='Día de función'),
        ),
        migrations.AddField(
            model_name='cine',
            name='observacion',
            field=models.TextField(blank=True, default='Función disponible solo fines de semana.', null=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='cine',
            name='productos_adicionales',
            field=models.TextField(blank=True, default='Canguil, Coca-Cola, hamburguesa', null=True, verbose_name='Productos adicionales'),
        ),
        migrations.AddField(
            model_name='detallecabanas',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de personas'),
        ),
        migrations.AddField(
            model_name='detallecabanas',
            name='precio_programa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio del programa'),
        ),
        migrations.AddField(
            model_name='detallecabanas',
            name='programa',
            field=models.CharField(choices=[('2D1N', '2 días / 1 noche'), ('3D2N', '3 días / 2 noches'), ('4D3N', '4 días / 3 noches')], default='2D1N', max_length=20, verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='detallecabanas',
            name='tipo_ocupacion',
            field=models.CharField(choices=[('Total', 'Ocupación total'), ('Sencilla', 'Ocupación sencilla'), ('Doble', 'Ocupación doble')], default='Total', max_length=20, verbose_name='Tipo de ocupación'),
        ),
        migrations.AddField(
            model_name='detallecine',
            name='productos_adicionales',
            field=models.TextField(blank=True, null=True, verbose_name='Productos adicionales'),
        ),
        migrations.AddField(
            model_name='detallecine',
            name='total_productos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total productos adicionales'),
        ),
        migrations.AddField(
            model_name='detallehabitaciones',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de personas'),
        ),
        migrations.AddField(
            model_name='detallehabitaciones',
            name='precio_programa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio del programa'),
        ),
        migrations.AddField(
            model_name='detallehabitaciones',
            name='programa',
            field=models.CharField(choices=[('2D1N', '2 días / 1 noche'), ('3D2N', '3 días / 2 noches'), ('4D3N', '4 días / 3 noches')], default='2D1N', max_length=20, verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='detallehabitaciones',
            name='tipo_ocupacion',
            field=models.CharField(choices=[('Total', 'Ocupación total'), ('Sencilla', 'Ocupación sencilla'), ('Doble', 'Ocupación doble')], default='Total', max_length=20, verbose_name='Tipo de ocupación'),
        ),
        migrations.AddField(
            model_name='detalleresort',
            name='combo_cabana',
            field=models.CharField(blank=True, default='Cabañas C3 hasta C8', max_length=100, null=True, verbose_name='Combo de cabaña'),
        ),
        migrations.AddField(
            model_name='detalleresort',
            name='punto_atencion',
            field=models.CharField(blank=True, default='Vistro', max_length=100, null=True, verbose_name='Punto de atención'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='anticipo_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Anticipo mínimo'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='fecha_limite_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de pago'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='porcentaje_anticipo',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Porcentaje de anticipo'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo pendiente'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='resortdia',
            name='combo_cabanas',
            field=models.CharField(blank=True, default='Combo con cabañas desde la C3 hasta la C8', max_length=150, null=True, verbose_name='Combo de cabañas'),
        ),
        migrations.AddField(
            model_name='resortdia',
            name='incluye',
            field=models.TextField(blank=True, default='Uso de instalaciones del resort. Incluye 2 shampoo y 2 jabones.', null=True, verbose_name='Incluye'),
        ),
        migrations.AddField(
            model_name='resortdia',
            name='indicaciones',
            field=models.TextField(blank=True, default='Las toallas se solicitan en Vistro. Vistro es el punto de atención para clientes del resort del día.', null=True, verbose_name='Indicaciones'),
        ),
        migrations.AddField(
            model_name='resortdia',
            name='punto_atencion',
            field=models.CharField(blank=True, default='Vistro', max_length=100, null=True, verbose_name='Punto de atención'),
        ),
        migrations.CreateModel(
            name='PagoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('PayPhone', 'Tarjeta / PayPhone'), ('Transferencia', 'Transferencia bancaria'), ('Recepcion', 'Pago en recepción')], max_length=30, verbose_name='Método de pago')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En revision', 'En revisión'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado'), ('Error', 'Error')], default='Pendiente', max_length=30, verbose_name='Estado del pago')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto total')),
                ('monto_anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto anticipo')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo pendiente')),
                ('client_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Client Transaction ID')),
                ('payphone_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='PayPhone Transaction ID')),
                ('authorization_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de autorización')),
                ('respuesta_payphone', models.JSONField(blank=True, null=True, verbose_name='Respuesta PayPhone')),
                ('banco_origen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco de origen')),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de comprobante')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes_transferencia/', verbose_name='Comprobante de transferencia')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion_hotel.reservas', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pago de reserva',
                'verbose_name_plural': 'Pagos de reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
