# Generated by Django 6.0.7 on 2026-07-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0002_tarifahospedaje_cine_dia_funcion_cine_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoreserva',
            name='link_pago_payphone',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de pago PayPhone'),
        ),
    ]
