# Generated by Django 6.0.7 on 2026-07-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0003_pagoreserva_link_pago_payphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En revision', 'En revisión'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=30, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='metodo_pago',
            field=models.CharField(choices=[('Sin seleccionar', 'Sin seleccionar'), ('Transferencia', 'Depósito o transferencia'), ('PayPhone', 'PayPhone por link'), ('Recepcion', 'Pago en recepción'), ('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], default='Sin seleccionar', max_length=30, verbose_name='Método de pago'),
        ),
    ]
