# Generated by Django 6.0.7 on 2026-07-26 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0004_alter_reservas_estado_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabanas',
            name='precio_2d1n_secundaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2D/1N - Ocupación secundaria'),
        ),
        migrations.AddField(
            model_name='cabanas',
            name='precio_2d1n_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2D/1N - Ocupación total'),
        ),
        migrations.AddField(
            model_name='cabanas',
            name='precio_3d2n_secundaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='3D/2N - Ocupación secundaria'),
        ),
        migrations.AddField(
            model_name='cabanas',
            name='precio_3d2n_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='3D/2N - Ocupación total'),
        ),
        migrations.AddField(
            model_name='cabanas',
            name='precio_4d3n_secundaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='4D/3N - Ocupación secundaria'),
        ),
        migrations.AddField(
            model_name='cabanas',
            name='precio_4d3n_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='4D/3N - Ocupación total'),
        ),
        migrations.AddField(
            model_name='cabanas',
            name='tipo_ocupacion_secundaria',
            field=models.CharField(choices=[('Sencilla', 'Ocupación sencilla'), ('Doble', 'Ocupación doble')], default='Sencilla', max_length=20, verbose_name='Tipo de ocupación secundaria'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='precio_2d1n_secundaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2D/1N - Ocupación secundaria'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='precio_2d1n_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2D/1N - Ocupación total'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='precio_3d2n_secundaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='3D/2N - Ocupación secundaria'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='precio_3d2n_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='3D/2N - Ocupación total'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='precio_4d3n_secundaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='4D/3N - Ocupación secundaria'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='precio_4d3n_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='4D/3N - Ocupación total'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='tipo_ocupacion_secundaria',
            field=models.CharField(choices=[('Sencilla', 'Ocupación sencilla'), ('Doble', 'Ocupación doble')], default='Sencilla', max_length=20, verbose_name='Tipo de ocupación secundaria'),
        ),
    ]
