# Generated by Django 6.0.7 on 2026-07-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0005_cabanas_precio_2d1n_secundaria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarifaHospedaje',
        ),
    ]
