# Generated by Django 6.0.7 on 2026-07-26 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0006_delete_tarifahospedaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabanas',
            name='nombre_cabana',
        ),
        migrations.RemoveField(
            model_name='habitaciones',
            name='piso',
        ),
    ]
