# Generated by Django 6.0.7 on 2026-08-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0007_remove_cabanas_nombre_cabana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_habitaciones', models.ImageField(blank=True, help_text='Imagen de la tarjeta de Habitaciones en el inicio.', null=True, upload_to='inicio/', verbose_name='Imagen de Habitaciones')),
                ('imagen_cabanas', models.ImageField(blank=True, help_text='Imagen de la tarjeta de Cabañas en el inicio.', null=True, upload_to='inicio/', verbose_name='Imagen de Cabañas')),
                ('imagen_cine', models.ImageField(blank=True, help_text='Imagen de la tarjeta de Cine en el inicio.', null=True, upload_to='inicio/', verbose_name='Imagen de Cine')),
                ('imagen_resort', models.ImageField(blank=True, help_text='Imagen de la tarjeta de Resort del Día en el inicio.', null=True, upload_to='inicio/', verbose_name='Imagen de Resort del Día')),
                ('imagen_hero', models.ImageField(blank=True, help_text='Fondo principal de la portada del inicio.', null=True, upload_to='inicio/', verbose_name='Imagen de fondo del hero')),
            ],
            options={
                'verbose_name': 'Configuración del inicio',
                'verbose_name_plural': 'Configuración del inicio',
            },
        ),
    ]
