# Generated by Django 6.0.7 on 2026-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0008_configuracioninicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninicio',
            name='mision',
            field=models.TextField(blank=True, help_text='Texto que se muestra en la sección de Misión de "Sobre nosotros".', null=True, verbose_name='Misión'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='vision',
            field=models.TextField(blank=True, help_text='Texto que se muestra en la sección de Visión de "Sobre nosotros".', null=True, verbose_name='Visión'),
        ),
    ]
