# Generated by Django 6.0.7 on 2026-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0009_configuracioninicio_mision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninicio',
            name='fondo_cabanas',
            field=models.ImageField(blank=True, help_text='Imagen de fondo de la portada de la página de Cabañas.', null=True, upload_to='inicio/fondos/', verbose_name='Fondo de Cabañas'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='fondo_cine',
            field=models.ImageField(blank=True, help_text='Imagen de fondo de la portada de la página de Cine.', null=True, upload_to='inicio/fondos/', verbose_name='Fondo de Cine'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='fondo_habitaciones',
            field=models.ImageField(blank=True, help_text='Imagen de fondo de la portada de la página de Habitaciones.', null=True, upload_to='inicio/fondos/', verbose_name='Fondo de Habitaciones'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='fondo_resort',
            field=models.ImageField(blank=True, help_text='Imagen de fondo de la portada de la página de Resort del Día.', null=True, upload_to='inicio/fondos/', verbose_name='Fondo de Resort del Día'),
        ),
    ]
