# Generated by Django 6.0.7 on 2026-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0010_configuracioninicio_fondo_cabanas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoreserva',
            name='numero_cuenta_origen',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de cuenta de origen'),
        ),
    ]
