# Generated by Django 6.0.7 on 2026-08-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0011_pagoreserva_numero_cuenta_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninicio',
            name='imagen_sobre_nosotros',
            field=models.ImageField(blank=True, help_text='Imagen de la portada de la página "Sobre nosotros".', null=True, upload_to='inicio/', verbose_name='Imagen de Sobre nosotros'),
        ),
    ]
