# Generated by Django 6.0.7 on 2026-08-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0012_configuracioninicio_imagen_sobre_nosotros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracioninicio',
            options={'verbose_name': 'Sobre nosotros', 'verbose_name_plural': 'Sobre nosotros'},
        ),
    ]
