# Generated by Django 6.0.7 on 2026-08-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0013_alter_configuracioninicio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_compromiso_imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la sección "Nuestro compromiso".', null=True, upload_to='inicio/', verbose_name='Compromiso: imagen'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_compromiso_parrafo',
            field=models.TextField(blank=True, null=True, verbose_name='Compromiso: párrafo'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_compromiso_titulo',
            field=models.CharField(blank=True, help_text='Título de la sección "Nuestro compromiso".', max_length=200, null=True, verbose_name='Compromiso: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_cta_parrafo',
            field=models.TextField(blank=True, null=True, verbose_name='CTA: párrafo'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_cta_titulo',
            field=models.CharField(blank=True, help_text='Título de la sección final de llamada a la acción.', max_length=200, null=True, verbose_name='CTA: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_hero_parrafo',
            field=models.TextField(blank=True, help_text='Texto de presentación de la página "Sobre nosotros".', null=True, verbose_name='Hero: párrafo'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_hero_titulo',
            field=models.CharField(blank=True, help_text='Título principal de la página "Sobre nosotros".', max_length=200, null=True, verbose_name='Hero: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_historia_imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la sección "Nuestra historia".', null=True, upload_to='inicio/', verbose_name='Historia: imagen'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_historia_parrafo_1',
            field=models.TextField(blank=True, null=True, verbose_name='Historia: párrafo 1'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_historia_parrafo_2',
            field=models.TextField(blank=True, null=True, verbose_name='Historia: párrafo 2'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_historia_titulo',
            field=models.CharField(blank=True, help_text='Título de la sección "Nuestra historia".', max_length=200, null=True, verbose_name='Historia: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_stat_1_etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estadística 1: etiqueta'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_stat_1_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estadística 1: número'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_stat_2_etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estadística 2: etiqueta'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_stat_2_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estadística 2: número'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_stat_3_etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estadística 3: etiqueta'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_stat_3_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estadística 3: número'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_stat_4_etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estadística 4: etiqueta'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_stat_4_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estadística 4: número'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_valor_1_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Valor 1: descripción'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_valor_1_titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor 1: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_valor_2_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Valor 2: descripción'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_valor_2_titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor 2: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_valor_3_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Valor 3: descripción'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_valor_3_titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor 3: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_valor_4_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Valor 4: descripción'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_valor_4_titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor 4: título'),
        ),
    ]
