# Generated by Django 6.0.7 on 2026-08-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0014_configuracioninicio_sn_compromiso_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoreserva',
            name='metodo_pago',
            field=models.CharField(choices=[('Transferencia', 'Transferencia bancaria'), ('Recepcion', 'Pago en recepción')], max_length=30, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='metodo_pago',
            field=models.CharField(choices=[('Sin seleccionar', 'Sin seleccionar'), ('Transferencia', 'Depósito o transferencia'), ('Recepcion', 'Pago en recepción'), ('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], default='Sin seleccionar', max_length=30, verbose_name='Método de pago'),
        ),
    ]
