# Generated by Django 6.0.7 on 2026-08-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0015_alter_pagoreserva_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cine',
            options={'verbose_name': 'Cine', 'verbose_name_plural': 'Cine'},
        ),
    ]
