# Generated by Django 5.2.17 on 2026-09-28 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0017_configuracioninicio_datos_bancarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninicio',
            name='cabanas_hero_kicker',
            field=models.CharField(blank=True, default='Cabañas', help_text='Etiqueta superior de la portada de Cabañas.', max_length=100, null=True, verbose_name='Cabañas hero: etiqueta (kicker)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='cabanas_hero_parrafo',
            field=models.TextField(blank=True, default='Cabañas rodeadas de naturaleza para disfrutar paz, comodidad y una conexión especial con el entorno.', help_text='Descripción de la portada de Cabañas.', null=True, verbose_name='Cabañas hero: párrafo'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='cabanas_hero_titulo',
            field=models.CharField(blank=True, default='Vive la experiencia de la Amazonía con privacidad', help_text='Título principal de la portada de Cabañas.', max_length=200, null=True, verbose_name='Cabañas hero: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='cine_hero_kicker',
            field=models.CharField(blank=True, default='Cine Arahuana', help_text='Etiqueta superior de la portada de Cine.', max_length=100, null=True, verbose_name='Cine hero: etiqueta (kicker)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='cine_hero_parrafo',
            field=models.TextField(blank=True, default='Disfruta de películas en un ambiente acogedor, rodeado de naturaleza, buena compañía y momentos especiales.', help_text='Descripción de la portada de Cine.', null=True, verbose_name='Cine hero: párrafo'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='cine_hero_titulo',
            field=models.CharField(blank=True, default='Noches de cine bajo las estrellas', help_text='Título principal de la portada de Cine.', max_length=200, null=True, verbose_name='Cine hero: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='habitaciones_hero_kicker',
            field=models.CharField(blank=True, default='Habitaciones', help_text='Etiqueta superior de la portada de Habitaciones.', max_length=100, null=True, verbose_name='Habitaciones hero: etiqueta (kicker)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='habitaciones_hero_parrafo',
            field=models.TextField(blank=True, default='Espacios diseñados para tu bienestar, donde cada detalle te conecta con la tranquilidad de la Amazonía.', help_text='Descripción de la portada de Habitaciones.', null=True, verbose_name='Habitaciones hero: párrafo'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='habitaciones_hero_titulo',
            field=models.CharField(blank=True, default='Confort y descanso en plena naturaleza', help_text='Título principal de la portada de Habitaciones.', max_length=200, null=True, verbose_name='Habitaciones hero: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='resort_hero_kicker',
            field=models.CharField(blank=True, default='Resort del día', help_text='Etiqueta superior de la portada de Resort del Día.', max_length=100, null=True, verbose_name='Resort hero: etiqueta (kicker)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='resort_hero_parrafo',
            field=models.TextField(blank=True, default='Accede a las áreas del resort para vivir bienestar, naturaleza, descanso y diversión en un solo lugar.', help_text='Descripción de la portada de Resort del Día.', null=True, verbose_name='Resort hero: párrafo'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='resort_hero_titulo',
            field=models.CharField(blank=True, default='Relájate y disfruta de un día perfecto', help_text='Título principal de la portada de Resort del Día.', max_length=200, null=True, verbose_name='Resort hero: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_compromiso_kicker',
            field=models.CharField(blank=True, default='Nuestro compromiso', help_text='Etiqueta superior en color resaltado de Compromiso.', max_length=100, null=True, verbose_name='Compromiso: etiqueta (kicker)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_cta_kicker',
            field=models.CharField(blank=True, default='Arahuana te espera', help_text='Etiqueta superior en color resaltado del llamado a la acción final.', max_length=100, null=True, verbose_name='CTA: etiqueta (kicker)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_hero_kicker',
            field=models.CharField(blank=True, default='Sobre nosotros', help_text='Etiqueta superior en color resaltado (ej. "Sobre nosotros").', max_length=100, null=True, verbose_name='Hero: etiqueta (kicker)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_historia_kicker',
            field=models.CharField(blank=True, default='Nuestra historia', help_text='Etiqueta superior en color resaltado de Historia.', max_length=100, null=True, verbose_name='Historia: etiqueta (kicker)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_mv_kicker',
            field=models.CharField(blank=True, default='Misión y Visión', help_text='Etiqueta superior en color resaltado de Misión y Visión.', max_length=100, null=True, verbose_name='Misión/Visión: etiqueta (kicker)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_mv_subtitulo',
            field=models.TextField(blank=True, default='Nuestros propósitos guían cada experiencia que compartimos contigo.', help_text='Texto introductorio de la sección Misión y Visión.', null=True, verbose_name='Misión/Visión: subtítulo'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_mv_titulo',
            field=models.CharField(blank=True, default='Lo que nos impulsa', help_text='Título principal de la sección Misión y Visión.', max_length=200, null=True, verbose_name='Misión/Visión: título'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_valores_kicker',
            field=models.CharField(blank=True, default='Nuestros valores', help_text='Etiqueta superior en color resaltado de Valores.', max_length=100, null=True, verbose_name='Valores: etiqueta (kicker)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_valores_subtitulo',
            field=models.TextField(blank=True, default='Trabajamos con principios que fortalecen la atención, la organización y la experiencia del visitante.', help_text='Texto introductorio de la sección de Valores.', null=True, verbose_name='Valores: subtítulo'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='sn_valores_titulo',
            field=models.CharField(blank=True, default='Lo que nos define', help_text='Título principal de la sección de Valores.', max_length=200, null=True, verbose_name='Valores: título'),
        ),
        migrations.AlterField(
            model_name='cabanas',
            name='precio_2d1n_secundaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2D/1N - Ocupacion secundaria'),
        ),
        migrations.AlterField(
            model_name='cabanas',
            name='precio_2d1n_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2D/1N - Ocupacion total'),
        ),
        migrations.AlterField(
            model_name='cabanas',
            name='precio_3d2n_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='3D/2N - Ocupacion total'),
        ),
        migrations.AlterField(
            model_name='cabanas',
            name='tipo_ocupacion_secundaria',
            field=models.CharField(choices=[('Sencilla', 'Ocupacion sencilla'), ('Doble', 'Ocupacion doble')], default='Sencilla', max_length=20, verbose_name='Tipo de ocupacion secundaria'),
        ),
        migrations.AlterField(
            model_name='cine',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='cine',
            name='dia_funcion',
            field=models.CharField(default='Sabado', max_length=30, verbose_name='Dia de funcion'),
        ),
        migrations.AlterField(
            model_name='cine',
            name='fecha_proyeccion',
            field=models.DateField(verbose_name='Fecha de proyeccion'),
        ),
        migrations.AlterField(
            model_name='cine',
            name='hora_proyeccion',
            field=models.TimeField(verbose_name='Hora de proyeccion'),
        ),
        migrations.AlterField(
            model_name='cine',
            name='observacion',
            field=models.TextField(blank=True, default='Funcion disponible solo fines de semana.', null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='cine',
            name='titulo_pelicula',
            field=models.CharField(max_length=150, verbose_name='Titulo de la pelicula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('Cedula', 'Cedula'), ('RUC', 'RUC'), ('Pasaporte', 'Pasaporte')], default='Cedula', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='numero_habitacion',
            field=models.CharField(max_length=10, unique=True, verbose_name='Numero de habitacion'),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='precio_2d1n_secundaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2D/1N - Ocupacion secundaria'),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='precio_2d1n_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2D/1N - Ocupacion total'),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='precio_3d2n_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='3D/2N - Ocupacion total'),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='tipo_habitacion',
            field=models.CharField(max_length=50, verbose_name='Tipo de habitacion'),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='tipo_ocupacion_secundaria',
            field=models.CharField(choices=[('Sencilla', 'Ocupacion sencilla'), ('Doble', 'Ocupacion doble')], default='Sencilla', max_length=20, verbose_name='Tipo de ocupacion secundaria'),
        ),
        migrations.AlterField(
            model_name='pagoreserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En revision', 'En revision'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado'), ('Error', 'Error')], default='Pendiente', max_length=30, verbose_name='Estado del pago'),
        ),
        migrations.AlterField(
            model_name='pagoreserva',
            name='metodo_pago',
            field=models.CharField(choices=[('Transferencia', 'Transferencia bancaria'), ('Recepcion', 'Pago en recepcion')], max_length=30, verbose_name='Metodo de pago'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En revision', 'En revision'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=30, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='metodo_pago',
            field=models.CharField(choices=[('Sin seleccionar', 'Sin seleccionar'), ('Transferencia', 'Deposito o transferencia'), ('Recepcion', 'Pago en recepcion'), ('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], default='Sin seleccionar', max_length=30, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='resortdia',
            name='capacidad_maxima',
            field=models.IntegerField(verbose_name='Capacidad maxima'),
        ),
        migrations.AlterField(
            model_name='resortdia',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='resortdia',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del area o servicio'),
        ),
        migrations.AlterField(
            model_name='resortdia',
            name='tipo_area',
            field=models.CharField(choices=[('piscina', 'Piscina'), ('habitacion_dia', 'Habitacion del Dia'), ('area_recreativa', 'Area Recreativa'), ('area_consumo', 'Area de Consumo'), ('restaurante', 'Restaurante'), ('spa', 'Spa'), ('cancha', 'Cancha'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de area'),
        ),
    ]
