# Generated by Django 5.2.17 on 2026-09-28 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0018_configuracioninicio_cabanas_hero_kicker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabanas',
            name='precio_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por día'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='precio_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por día'),
        ),
    ]
