# Generated by Django 5.2.17 on 2026-09-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0019_cabanas_precio_dia_habitaciones_precio_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninicio',
            name='color_dorado',
            field=models.CharField(blank=True, default='#d9aa38', help_text='Color para kickers naranjas/dorados, estrellas y destacados.', max_length=20, null=True, verbose_name='Color dorado / acento'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='color_fondo',
            field=models.CharField(blank=True, default='#fff6e4', help_text='Color de fondo principal de las páginas.', max_length=20, null=True, verbose_name='Color de fondo (Crema / Claro)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='color_primario',
            field=models.CharField(blank=True, default='#07351f', help_text='Color principal de la marca, fondos oscuros y barras.', max_length=20, null=True, verbose_name='Color primario (Verde oscuro)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='color_secundario',
            field=models.CharField(blank=True, default='#0f6848', help_text='Color para botones secundarios, acentos de navegación y hover.', max_length=20, null=True, verbose_name='Color secundario (Verde medio)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='color_texto',
            field=models.CharField(blank=True, default='#163024', help_text='Color principal para textos y títulos.', max_length=20, null=True, verbose_name='Color de texto principal'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='fuente_principal',
            field=models.CharField(blank=True, choices=[('Poppins', 'Poppins (Moderna y limpia)'), ('Montserrat', 'Montserrat (Geométrica contemporánea)'), ('Inter', 'Inter (Minimalista digital)'), ('Roboto', 'Roboto (Neutral y clara)'), ('Open Sans', 'Open Sans (Amigable y legible)'), ('Lato', 'Lato (Cálida y balanceada)'), ('Raleway', 'Raleway (Elegante delgada)')], default='Poppins', help_text='Fuente para párrafos, botones, menús y textos generales.', max_length=50, null=True, verbose_name='Tipografía de texto (Cuerpo)'),
        ),
        migrations.AddField(
            model_name='configuracioninicio',
            name='fuente_titulos',
            field=models.CharField(blank=True, choices=[('Playfair Display', 'Playfair Display (Elegante clásico)'), ('Cinzel', 'Cinzel (Lujoso mayúsculas)'), ('Merriweather', 'Merriweather (Serif moderna)'), ('Cormorant Garamond', 'Cormorant Garamond (Resort & Spa)'), ('Poppins', 'Poppins (Moderna sin serifas)'), ('Montserrat', 'Montserrat (Fuerte y visible)')], default='Playfair Display', help_text='Fuente para títulos (H1, H2, H3), encabezados y banners.', max_length=50, null=True, verbose_name='Tipografía de títulos'),
        ),
    ]
