# Generated by Django 5.2.17 on 2026-09-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_hotel', '0020_configuracioninicio_color_dorado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecabanas',
            name='programa',
            field=models.CharField(choices=[('2D1N', '2 días / 1 noche'), ('3D2N', '3 días / 2 noches'), ('4D3N', '4 días / 3 noches'), ('Personalizado', 'Personalizado / Otro')], default='2D1N', max_length=20, verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='detallehabitaciones',
            name='programa',
            field=models.CharField(choices=[('2D1N', '2 días / 1 noche'), ('3D2N', '3 días / 2 noches'), ('4D3N', '4 días / 3 noches'), ('Personalizado', 'Personalizado / Otro')], default='2D1N', max_length=20, verbose_name='Programa'),
        ),
    ]
