"""
Configuracion Django del proyecto Arahuana Resort.

Centraliza apps instaladas, middleware, templates, base de datos, archivos
estaticos/media y variables de entorno usadas por el backend.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
try:
    # Optional: load environment variables from a .env file in BASE_DIR
    from dotenv import load_dotenv  # type: ignore
except Exception:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
if load_dotenv:
    load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment; use a safe dev fallback only for local development.
SECRET_KEY = os.getenv("SECRET_KEY", "clave-dev-solo-local")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:8000,http://127.0.0.1:8000,http://0.0.0.0:8000,http://localhost:8001,http://127.0.0.1:8001,http://0.0.0.0:8001",
    ).split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'gestion_hotel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'gestion_hotel.middleware.GerenteAdminRedirectMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'arahuana_resort.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'gestion_hotel' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'arahuana_resort.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'hotel_arahuana_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Default Auto Field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===========================================================================
# CONFIGURACIÓN PERSONALIZADA DE JAZZMIN (TEMA PARA EL HOTEL ARAHUANA)
# ===========================================================================

JAZZMIN_SETTINGS = {
    "site_title": "Panel de Gestión Hotelera",
    "site_header": "Sistema Hotelero Arahuana",
    "site_brand": "Panel de Gestión",
    "welcome_sign": "Bienvenido al Panel de Gestión Hotelera",
    "copyright": "Sistema Hotelero Arahuana © 2026",

    "site_logo": "img/logo.jpg",
    "login_logo": "img/logo.jpg",
    "site_icon": "img/logo.jpg",

    "custom_css": "css/admin_custom.css",

    "search_model": "gestion_hotel.Cliente",

    "order_with_respect_to": [
        "auth.User",
        "auth.Group",
        "gestion_hotel.Cliente",
        "gestion_hotel.Habitaciones",
        "gestion_hotel.Cabanas",
        "gestion_hotel.Cine",
        "gestion_hotel.ResortDia",
        "gestion_hotel.Reservas",
    ],

    "hide_models": [
        "gestion_hotel.DetalleHabitaciones",
        "gestion_hotel.DetalleCabanas",
        "gestion_hotel.DetalleCine",
        "gestion_hotel.DetalleResort",
    ],

    "icons": {
        "auth.User": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog",

        "gestion_hotel.Cliente": "fas fa-users",
        "gestion_hotel.Habitaciones": "fas fa-bed",
        "gestion_hotel.Cabanas": "fas fa-home",
        "gestion_hotel.Cine": "fas fa-film",
        "gestion_hotel.ResortDia": "fas fa-water",
        "gestion_hotel.Reservas": "fas fa-calendar-check",
    },
    "topmenu_links": [
        {"name": "Dashboard Gerencial", "url": "gestion:gerente_dashboard", "new_window": False},
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver Reservas", "model": "gestion_hotel.Reservas"},
        {"name": "Ver Clientes", "model": "gestion_hotel.Cliente"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "minty",
    "default_theme_mode": "dark",
    "navbar": "navbar-dark navbar-teal",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-teal",
    "accent": "accent-teal",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "sidebar_nav_child_indent": True,
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'gestion_hotel' / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================
# DATOS BANCARIOS DEL HOTEL
# ============================================================

BANCO_1_NOMBRE = os.getenv("BANCO_1_NOMBRE", "Banco principal")
BANCO_1_TIPO = os.getenv("BANCO_1_TIPO", "Cuenta")
BANCO_1_CUENTA = os.getenv("BANCO_1_CUENTA", "")
BANCO_1_TITULAR = os.getenv("BANCO_1_TITULAR", "")
BANCO_1_IDENTIFICACION = os.getenv("BANCO_1_IDENTIFICACION", "")
BANCO_1_CORREO = os.getenv("BANCO_1_CORREO", "")

BANCO_2_NOMBRE = os.getenv("BANCO_2_NOMBRE", "Banco secundario")
BANCO_2_TIPO = os.getenv("BANCO_2_TIPO", "Cuenta")
BANCO_2_CUENTA = os.getenv("BANCO_2_CUENTA", "")
BANCO_2_TITULAR = os.getenv("BANCO_2_TITULAR", "")
BANCO_2_IDENTIFICACION = os.getenv("BANCO_2_IDENTIFICACION", "")
BANCO_2_CORREO = os.getenv("BANCO_2_CORREO", "")

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:8000',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:8000',
]

# ============================================================
# CONFIGURACIÓN DE CORREO SMTP
# ============================================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))

EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes")
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in ("true", "1", "yes")

EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "20"))

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# Evita mezcla incorrecta entre TLS y SSL
if EMAIL_PORT == 465:
    EMAIL_USE_SSL = True
    EMAIL_USE_TLS = False
elif EMAIL_PORT == 587:
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    
CORS_ALLOW_CREDENTIALS = True

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
